dashboard/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dashboard.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^defect_notice/', include('defect_notice.urls')), # Add this tuple to include app urls
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^assessment/', include('assessment.urls')),
    url(r'media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

defect_notice/forms.py
__author__ = 'anithrao'
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from defect_notice.models import *
from datetime import date

#class ContactForm(forms.Form):
    #subject = forms.CharField(max_length=100)
    #message = forms.CharField()
    #sender = forms.EmailField()
    #cc_myself = forms.BooleanField(required=False)

class DefectForm(forms.Form):
    # user_name = forms.ModelChoiceField(LoginLookup.objects.all(),error_messages={'required': 'Please select User ID'},empty_label=None)
    site_multi = forms.ModelMultipleChoiceField(SiteDetailsLookup.objects.all(),label='Site Code',error_messages={'required': 'Please select one or more Site Code/s'})
    tt_number = forms.CharField(max_length=128, label='Trouble Ticket Number', required=False)
    incident_date = forms.DateField(label="Incident Date", required=True, input_formats=['%m-%d-%Y'],initial=date.today().strftime('%m-%d-%Y'),
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
        help_text="Format: MM-DD-YYYY",error_messages={'required': 'Please pick a date'})
    indicator_source = forms.ModelChoiceField(DefectSourceLookup.objects.all(), empty_label=None,label="Source of First Indication", error_messages={'required': 'Please provide source of the defect.'})
    critical_load = forms.TypedChoiceField(label="Critical Load Loss", widget=forms.RadioSelect, choices=((1, 'Yes'), (0, 'No')),initial=0, error_messages={'required': 'Please select severity of load'})
    large_scale = forms.TypedChoiceField(label="Large Scale Event", widget=forms.RadioSelect, choices=((1, 'Yes'), (0, 'No')),initial=0, error_messages={'required': 'Please select scale of defect'})
    division_asset = forms.ModelChoiceField(InfrastructureDivisionLookup.objects.all(), empty_label=None,label="Infrastructure Division")
    system_asset = forms.ModelChoiceField(InfrastructureSystemLookup.objects.all(), empty_label=None, label="Infrastructure System")
    subsystem_asset = forms.CharField(label="Infrastructure Subsystem", max_length=128,error_messages={'required': 'Please select Subsystem asset' })
    manufacturer_asset = forms.CharField(label="Manufacturer", max_length=128, error_messages={'required': 'Please add manufacturer asset'})
    model_number = forms.CharField(label="Model Number", max_length=128)
    referenceFile = forms.FileField(label='Reference File Upload', help_text='max 50 MB', initial='none')
    filename = forms.CharField(widget=forms.HiddenInput(),initial='none')
    defect_synopsis = forms.CharField(label="Synopsis", required=False, widget=forms.Textarea(attrs={'rows': 5, 'cols': 100}))
    notifier_email = forms.EmailField(widget=forms.HiddenInput(), initial='anithrao@amazon.com')
    approved = forms.TypedChoiceField(widget=forms.HiddenInput(), choices=((1, 'Yes'), (0, 'No')), initial=0)
    approvalDate = forms.DateField(widget=forms.HiddenInput(), input_formats=['%m-%d-%Y'], initial=date.today().strftime('%m-%d-%Y'))


class SearchDefectForm(forms.Form):
    id = forms.IntegerField(label="Enter ID: ", min_value=1, error_messages={'required': 'Please enter Defect Id.'})
    #defectdetails = forms.ModelChoiceField(DefectDetails._get_pk_val().all, label="Enter ID: ",error_messages={'required': 'Please enter Defect Id.'})
    
    
class ApproveDefectForm(forms.Form):
    id = forms.IntegerField(widget=forms.HiddenInput())
    # username = forms.ModelChoiceField(LoginLookup.objects.all(),empty_label=None, label= 'User name', error_messages={'required': 'Please select User ID'})
    # site = forms.ModelMultipleChoiceField(SiteDetailsLookup.objects.all(),label='Site Code',error_messages={'required': 'Please select one or more Site Code/s'}, help_text='Select one or many Site codes')
    site = forms.CharField(max_length=250, label='Site/s', error_messages={'required': 'Please enter Site code/s'})
    ttnumber = forms.CharField(max_length=128, label='Trouble Ticket Number', required=False,)
    incidentDate = forms.DateField(label="Incident Date", required=True,input_formats=['%m-%d-%Y'],initial=date.today().strftime('%m-%d-%Y'),
        widget=forms.DateInput(attrs={'class': 'datepicker'}),
        help_text="Format: MM-DD-YYYY",error_messages={'required': 'Please pick a date' })
    defectSource_id = forms.ModelChoiceField(DefectSourceLookup.objects.all(), empty_label=None,label="Source of First Indication", initial=0, help_text="Select a source", error_messages={'required': 'Please select User ID'})
    critical = forms.TypedChoiceField(label="Critical Load Loss", widget=forms.RadioSelect, choices=((1, 'Yes'), (0, 'No')),initial=0, error_messages={'required': 'Please select severity of load'})
    largeScale = forms.TypedChoiceField(label="Large Scale Event", widget=forms.RadioSelect, choices=((1, 'Yes'), (0, 'No')),initial=0, error_messages={'required': 'Please select scale of defect'})
    infrastructureDivision_id = forms.ModelChoiceField(InfrastructureDivisionLookup.objects.all(), empty_label=None, label="Infrastructure Division", error_messages={'required': 'Please select User ID'})
    infrastructureSystem_id = forms.ModelChoiceField(InfrastructureSystemLookup.objects.all(), empty_label=None,label="Infrastructue System", error_messages={'required': 'Please select User ID'})
    infrastructureSubsystem = forms.CharField(label="Infrastructure Subsystem", max_length=128,error_messages={'required': 'Please select Subsystem asset' })
    assetManufacturer = forms.CharField(label="Manufacturer", max_length=128, error_messages={'required': 'Please add manufacturer asset'})
    assetModelNumber = forms.CharField(label="Model Number", max_length=128)
    filename = forms.CharField(max_length=250, label='File Uploaded')
    # filename = forms.URLField(max_length=250, label='File Uploaded')
    defectSynopsis = forms.CharField(label="Synopsis", required=False, widget=forms.Textarea(attrs={'rows': 5, 'cols': 100}))
    notifierEmail = forms.EmailField(widget=forms.HiddenInput(), initial='anithrao@amazon.com')
    username = forms.CharField(widget=forms.HiddenInput())
    approved = forms.TypedChoiceField(label="Approve", widget=forms.RadioSelect, choices=((1, 'Yes'), (0, 'No')), error_messages={'required': 'Please select approval'})
    approvalDate = forms.DateField(widget=forms.HiddenInput(), input_formats=['%m-%d-%Y'], initial=date.today().strftime('%m-%d-%Y'))


    
    

templates/base.html
<!DOCTYPE html>
<html>

<head>
    {% block external %}
{#        <link rel="stylesheet" href="http://thecodeplayer.com/uploads/fonts/fontawesome/css/font-awesome.min.css)">#}
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"/>
    {% endblock %}
    <title>Defect Notice</title>
    {% load static from staticfiles %}

    <script type="text/javascript" src="{% static 'js/jquery-latest.min.map.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/jquery-1.10.2.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery.tablesorter.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
    <!-- prefix free to deal with vendor prefixes -->
    <script type="text/javascript" src="{% static 'js/prefixfree-1.0.7.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/search_defectnotice.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.multiple.select.js' %}" ></script>

    <script type="text/javascript" src="{% static 'js/jquery.easing.min.js' %}" ></script>

{#    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/jqueri-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/multiple-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">


<!--{#<script type="application/javascript">#}-->
<!--{#/*jQuery time*/#}-->
<!--{#$(document).ready(function(){#}-->
<!--{#	$("#accordian h3").click(function(){#}-->
<!--{#		//slide up all the link lists#}-->
<!--{#		$("#accordian ul ul").slideUp();#}-->
<!--{#		//slide down the link list below the h3 clicked - only if its closed#}-->
<!--{#		if(!$(this).next().is(":visible"))#}-->
<!--{#		{#}-->
<!--{#			$(this).next().slideDown();#}-->
<!--{#		}#}-->
<!--{#	})#}-->
<!--{#})#}-->
<!--{#</script>#}-->
<script type="application/javascript">
/*jQuery - highlight selected left nav menu item*/
$(document).ready(function(){
var str=location.href.toLowerCase();
$("#accordian ul ul li a").each(function() {
if (str.indexOf(this.href.toLowerCase()) > -1) {
 $("#accordian ul ul li.selected").removeClass("selected");
$(this).parent().addClass("selected");
}
 });
 })
jQuery('input.date').each(function(){
    jQuery(this).datepicker({dateFormat:'dd/mm/yy', changeMonth: true,    stepMonths: 12, showAnim:"slideDown" });
    jQuery('#ui-datepicker-div .ui-helper-hidden-accessible').css("position", "absolute !important");
    jQuery('#ui-datepicker-div').css('clip', 'auto');
});
</script>

<script type="text/javascript">
    /* sort report table*/
    $(document).ready(function() {
        $("#myTable").tablesorter();
        $(".datepicker").datepicker( { maxDate: new Date()} );
    });
</script>
<script type="text/javascript">
    $(function() {
        $(".datepicker").datepicker();
        $(".datepicker").datepicker( { maxDate: new Date()} );
        $('#id_site_multi').multipleSelect();
{#        $('#id_site').multipleSelect();#}
    });
    $(function() {
    $( "#tabs" ).tabs();
    $( "#tabs" ).tabs({
      event: "mouseover"
    });
  });

</script>

  </head>
  <body>

    <header>
        <div style="float:left;"><a href="/"><img src="{% static 'images/DCQSR_logoWT.jpg' %}" alt="" /></a>
            <a href="/"><img src="{% static 'images/dcqsrLogo.jpg' %}" alt="" /></a></div><hr>
    </header><!-- container>-->
<div class="container">
{#    <div class="content">#}
        <div id="accordian">
        <ul>
            <li>
                <h3><span class="icon-dashboard"></span>Field Defect Notifications</h3>
                <ul>
                    <li><a href="/defect_notice/about">About Field Defect</a></li>
                    <li><a href="/defect_notice/add">Defect Form</a></li>
                    <li><a href="/defect_notice/report">Defect Report</a></li>
                </ul>
            </li>
            <!-- we will keep this LI open by default -->
            <li>
                <h3><span class="icon-tasks"></span>Datacenter Acceptance</h3>
                <ul>
                    <li><a href="#">Form 1</a></li>
                    <li><a href="#">Report 1</a></li>
                    <li><a href="#">Form 2</a></li>
                    <li><a href="#">Report 2</a></li>
                </ul>
            </li>
            <li>
                <h3><span class="icon-calendar"></span>Site Reliability</h3>
                <ul>
                    <li><a href="/assessment/monthly">Monthly Self Assessment Form</a></li>
                    <li><a href="#">Monthly Self Assessment Report</a></li>
                    <li><a href="#">Quarterly Self Assessment Form</a></li>
                    <li><a href="#">Quarterly Self Assessment Report</a></li>
                    <li><a href="#">AWS Quarterly Assessment Form</a></li>
                    <li><a href="#">AWS Quarterly Assessment report</a></li>
                </ul>
            </li>
            <li>
                <h3>Datacenter Implementations</h3>
                <ul>
                    <li><a href="#">Master Schedules</a></li>
                </ul>
            </li>
            <li>
                <h3>Quality Metrics</h3>
                <ul>
                    <li><a href="#">Datacenter Health</a></li>
                    <li><a href="#">PUE Dashboard</a></li>
                </ul>
            </li>
            <li>
                <h3>Documents</h3>
                <ul>
                    <li><a href="#">All Sites</a></li>
                </ul>
            </li>
        </ul>
        </div>

        {% block content %}
        {% endblock %}
{#    </div>#}
</div>
<div id="footer">

        <div class="rounded-img" style="">
            <a target="_blank" href="https://dco-docs-cf.amazon.com/dashboard.action">
                <img src="{% static 'images/DCPortalLogo.png' %}" alt="DC Portal" />
            </a>
        </div>
        <div class="business_card">
            <h3> Need help?</h3>
            <ul>
                <li>FAQ </li>
                <li>Documentation</li>
                <li>Contact Us: dcq-sr@amazon.com</li>
            </ul>
            <div class="browser_support">
                <a href="https://w.amazon.com/?DTUX/Browser_Support_Policy">Browser Support Policy</a>
            </div>
        </div>
</div>
  </body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block external %}
{% load static %}
{% endblock %}

{% block content %}
    <div class="contentinner">
        <div id="tabs" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
            <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" role="tablist">
                <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab" tabindex="0" aria-controls="tabs-1" aria-labelledby="ui-id-1" aria-selected="true"><a href="#tabs-1" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-1">Executive Summary</a></li>
                <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tabs-2" aria-labelledby="ui-id-2" aria-selected="false"><a href="#tabs-2" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-2">Vision</a></li>
                <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tabs-3" aria-labelledby="ui-id-3" aria-selected="false"><a href="#tabs-3" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-3">Mission</a></li>
                <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tabs-4" aria-labelledby="ui-id-4" aria-selected="false"><a href="#tabs-4" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-4">Goals</a></li>
                <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tabs-5" aria-labelledby="ui-id-5" aria-selected="false"><a href="#tabs-5" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-5">Key Success Factors</a></li>
                <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tabs-6" aria-labelledby="ui-id-6" aria-selected="false"><a href="#tabs-6" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-6">Primary Customers</a></li>
                <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tabs-7" aria-labelledby="ui-id-7" aria-selected="false"><a href="#tabs-7" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-7">Products and Services</a></li>
            </ul>
            <div id="tabs-1" aria-labelledby="ui-id-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="true" aria-hidden="false">
                <p>The Data Center Quality and Site Reliability (DCQ&SR) team is a new team (Q4 2013) that is tasked with inspecting and determining if new data center builds are “OPS capable” along with the risk profiling, site auditing, data center health and data center improvement projects of existing operational data centers in the Americas. In addition to determining if a new data center is “OPS capable”, the team will recommend mitigating actions to ensure capacity demands are 100% achieved for AWS. For existing operating data centers, the team will use risk profiling and data center audits to identify defects and will use a data center health portal to systematically trend the metrics to identify improvement initiatives.The Data Center Quality and Site Reliability (DCQ&SR) team is a new team (Q4 2013) that is tasked with inspecting and determining if new data center builds are “OPS capable” along with the risk profiling, site auditing, data center health and data center improvement projects of existing operational data centers in the Americas. In addition to determining if a new data center is “OPS capable”, the team will recommend mitigating actions to ensure capacity demands are 100% achieved for AWS. For existing operating data centers, the team will use risk profiling and data center audits to identify defects and will use a data center health portal to systematically trend the metrics to identify improvement initiatives.</p>
                <p>Specifically, the DCQ&SR team focuses on the ongoing improvement of a quality program across the platform explicit to power systems, mechanical cooling systems, controls, security, data center operations and staffing. The quality program will have defined feedback loops into Engineering Design, Construction, Commissioning, Operations and Training.</p>
                <p>In the joint effort to bring AWS availability to the next level, the DCQ&SR team will work within Amazonian model approach for all work and reporting. The team’s pragmatic approach will ensure the quality bar remains high by certifying the delivery of high quality work, while still demanding it of others’ as well. In addition, DCQ&SR wants to raise the quality bar by encouraging that our teams deliver high quality products, services and solutions in supporting our company goals. Furthermore, DCQ&SR wants to teach and coach employees about setting their own standards of meeting the customer expectations. Finally, DCQ&SR will work in supporting the best interest of the company and our customers given the various constraints that are present for any given situation.</p>
                <p>The team will personify the leadership principle: <i>Insist on the Highest Standards</i> - Leaders ensure that defects do not get sent down the line and that problems are fixed so they stay fixed.</p>
            </div>
            <div id="tabs-2" aria-labelledby="ui-id-2" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
                <p>In a joint effort with Engineering Design, Construction, Commissioning, Operations and Training teams, we would deliver new data centers on time, on budget and without defects; in addition, all defects in operational data centers would be systematically identified and removed from the system based on the risk profiling of the defect to ensure zero ops controllable outages in the Americas.</p>
            </div>
            <div id="tabs-3" aria-labelledby="ui-id-3" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
                <p>Strive for prevention of failure, defect reduction and increased customer satisfaction</p>
                <ul>
                    <li style="list-style-type: disc;">Research and develop new methods and standards to drive site reliability</li>
                    <li style="list-style-type: disc;">Proactively communicate and share knowledge</li>
                    <li style="list-style-type: disc;">Apply the knowledge to enhance our products, processes and services</li>
                    <li style="list-style-type: disc;">Continually monitor and improve our performance against set targets</li>
                </ul>
            </div>
            <div id="tabs-4" aria-labelledby="ui-id-4" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
                <p>GOALS - 2014 GOALS AND OBJECTIVES</p>
                <ul><li style="list-style-type: disc;">Building of the Quality Team</li>
                    <li style="list-style-type: disc;">Data Center Acceptance Program</li>
                    <ul style="padding-left: 10px;">
                        <li style="list-style-type:circle;">Owner Project Requirementso	Owner Project Requirements</li>
                        <li style="list-style-type:circle;">Infra Sauron Report</li>
                    </ul>
                    <li style="list-style-type: disc;">Staff Recommendations</li>
                    <li style="list-style-type: disc;">Data Center Health Dashboard</li>
                    <li style="list-style-type: disc;">Site Reliability Audit Program</li>
                    <ul style="padding-left: 10px;">
                        <li style="list-style-type:circle;">Monthly Inspection Program</li>
                    </ul>
                    <li style="list-style-type: disc;">DCQ&SR Workflow Process</li>
                    <ul style="padding-left: 10px;">
                        <li style="list-style-type:circle;">Change Management Communication</li>
                        <li style="list-style-type:circle;">Field Defect Notification</li>
                        <li style="list-style-type:circle;">Weekly Project Tracker</li>
                    </ul>
                    <li style="list-style-type: disc;">Expand the quality program throughout the Americas </li>
                </ul>
            </div>
            <div id="tabs-5" aria-labelledby="ui-id-5" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
                <ul>
                    <li style="list-style-type: disc;">Reduction of AWS outages - zero ops controllable outages in the Americas</li>
                    <li style="list-style-type: disc;">Defining the Key Performance Indicators (KPIs) to provide transparency into control mechanisms to ensure zero ops controllable outages</li>
                    <li style="list-style-type: disc;">Real time quantitative measuring of DC Health at the individual data center level along with cluster-wide health based on KPIs</li>
                    <li style="list-style-type: disc;">Creation of new policies, procedures and practices to the OPS teams to Increase operational readiness or process engineering of existing procedures and practices to proactively mitigate operational risk</li>
                    <li style="list-style-type: disc;">Field defect notification tool to effectively notify the team of any discovered infrastructure issues along with systematic tracking and trending analysis
</li>
                    <li style="list-style-type: disc;">Project completion of improvement projects versus target without incident</li>
                    <li style="list-style-type: disc;">Identification of training gaps</li>
                </ul>
            </div>
            <div id="tabs-6" aria-labelledby="ui-id-6" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
                <ul>
                    <li style="list-style-type: disc;">AWS</li>
                    <li style="list-style-type: disc;">Service Providers</li>
                    <ul style="padding-left: 10px;">
                        <li style="list-style-type:circle;">Engineering Design</li>
                        <li style="list-style-type:circle;">Construction</li>
                        <li style="list-style-type:circle;">Commissioning</li>
                        <li style="list-style-type:circle;">Training</li>
                    </ul>
                </ul>
            </div>
            <div id="tabs-7" aria-labelledby="ui-id-7" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
                <ul>
                    <li style="list-style-type: disc;">Products:</li>
                    <ul style="padding-left: 10px;">
                        <li style="list-style-type:circle;">AWS acceptance checklist for new construction projects with mitigation actions along with production of a site binder that will include all documentation, site operability items, training and miscellaneous turnover items</li>
                        <li style="list-style-type:circle;">Formal DC walkthroughs and audit templates and reports along with submission of corrective actions based on DCQ&SR audits</li>
                        <li style="list-style-type:circle;">DCI weekly project tracker and communication </li>
                    </ul>
                    <li style="list-style-type: disc;">Services:</li>
                    <ul style="padding-left: 10px;">
                        <li style="list-style-type:circle;">Real time quantitative measuring of DC Health at the individual data center level along with cluster-wide health based on established KPIs </li>
                        <li style="list-style-type:circle;">Incident reporting and communication (Amazon Field Defect Notice)</li>
                        <li style="list-style-type:circle;">Risk profiling for all data centers in the Americas</li>
                        <li style="list-style-type:circle;">Best practice guidance for the creation of new policies, procedures, and practices to the OPS teams to increase operational readiness or process engineering of existing procedures and practices to proactively mitigate operational risk</li>
                    </ul>
                </ul>
            </div>
        </div>
    </div>
{#    <a href="/defect_notice/add_defectnotice/">Defect_Notice Form</a><br />#}
{#    <a href="/defect_notice/about">About</a><br />#}
{#    <img src="{% static "images/main_logo.jpeg" %}" alt="" />#}
{#    <img src="media/main_logo.jpeg" alt="" />#}
{% endblock %}

{#<!DOCTYPE html>#}
{#{% load static %}#}
{#<html>#}
{#<head>#}
{#    <title>Defect Notice</title>#}
{#    <link rel="stylesheet" href="{% static "css/base.css" %}" /> <!-- CSS -->#}
{#    <script src="{% static "js/jquery.js" %}"></script> <!-- JavaScript -->#}
{#</head>#}
{#<body>#}
{#    <h1>Notice Defect</h1>#}
{#</body>#}
{#</html>#}